name: Build and Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: Build React App
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@users.noreply.github.com'
          git remote add origin_with_token https://$GH_TOKEN@github.com/wh1t3h47/ts-statistics.git
          git push origin_with_token master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
