name: Build and Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: Build React App
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git config --global credential.helper store
          echo "${GH_TOKEN}" | git credential-store store
          yarn run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
